### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by AmilkarVladimiR** [SistemasTecTlaxiaco/actividad-1-infografia-AmilkarVladimiR#2]
[CICLO DE VIDA Y FACES DEL SOFTWARE-Amilkar-Vladimir Reyes .pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-AmilkarVladimiR/files/9465798/CICLO.DE.VIDA.Y.FACES.DEL.SOFTWARE-Amilkar-Vladimir.Reyes.pdf)

**Comment by ang3-l32** [comment]
calificaciòn;19.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
